config/routes.rb
Rails.application.routes.draw do
  resources :runtimes
  resources :mrpjobs
  root 'welcome#index'
  
  get 'graph/index'
  get 'graph/data', :defaults => { :format => 'json' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/mrpjob.rb
class Mrpjob < ApplicationRecord
    has_many :runtimes, :dependent => :destroy
    accepts_nested_attributes_for :runtimes
end

app/models/runtime.rb
class Runtime < ApplicationRecord
  belongs_to :mrpjob

  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :date, presence: true
  validates :mrpjob_id, presence: true
end

app/controllers/graph_controller.rb
class GraphController < ApplicationController
  def index
    if params.has_key?(:graph_id)
      $graph_id = params[:graph_id].to_i
    else
      $graph_id = 0
    end
    @mrpjob = Mrpjob.all.order('id ASC')
    @mrpname = @mrpjob[$graph_id].description
  end

  def data
    @mrpjob = Mrpjob.all.order('id ASC')
    @runtimes = Runtime.all
    @array_of_times = []
    @mrpjob[$graph_id].runtimes.order('date DESC').each do |f|
                            @start_time = f.start_time.strftime('%H:%M')
                            @end_time = f.end_time.strftime('%H:%M')
                            @date= f.date.strftime('%Y/%m/%d')

                            if (f.start_time > f.end_time)
                              @completion_time = ((f.end_time - f.start_time)/60).floor + 1440
                            else
                              @completion_time = ((f.end_time - f.start_time)/60).floor
                            end

                            @array_of_times.push(completion_time: @completion_time, date: @date)
    end
    respond_to do |format|
      format.json {
        render :json => @array_of_times
      }
    end
  end
end

app/controllers/mrpjobs_controller.rb
class MrpjobsController < ApplicationController
  before_action :set_mrpjob, only: [:show, :edit, :update, :destroy]

  # GET /mrpjobs
  # GET /mrpjobs.json
  def index
    @mrpjobs = Mrpjob.all
  end

  # GET /mrpjobs/1
  # GET /mrpjobs/1.json
  def show
    @amount = params[:amount].to_f

    if @amount.nil? || @amount == 0
      @time_to_sort = Time.now.to_date-45.days
    else
      @time_to_sort = Time.now.to_date-@amount.days
    end

    @sorting = @mrpjob.runtimes.order("date DESC")
    @completion_time = []
    @mrpjob.runtimes.each do |runtime|
      #if (runtime.date > Time.now.to_date-45.days)
      if (runtime.date > @time_to_sort)
        if (runtime.start_time > runtime.end_time)
          @completion_time.push(((runtime.end_time - runtime.start_time)/60) + 1440)
        else
          @completion_time.push((runtime.end_time - runtime.start_time)/60)
        end
      end
    end
    @running_average = (@completion_time.sum / @completion_time.size).round(2)
  end

  # GET /mrpjobs/new
  def new
    @mrpjob = Mrpjob.new
  end

  # GET /mrpjobs/1/edit
  def edit
  end

  # POST /mrpjobs
  # POST /mrpjobs.json
  def create
    @mrpjob = Mrpjob.new(mrpjob_params)

    respond_to do |format|
      if @mrpjob.save
        format.html { redirect_to @mrpjob, notice: 'Mrpjob was successfully created.' }
        format.json { render :show, status: :created, location: @mrpjob }
      else
        format.html { render :new }
        format.json { render json: @mrpjob.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mrpjobs/1
  # PATCH/PUT /mrpjobs/1.json
  def update
    respond_to do |format|
      if @mrpjob.update(mrpjob_params)
        format.html { redirect_to @mrpjob, notice: 'Mrpjob was successfully updated.' }
        format.json { render :show, status: :ok, location: @mrpjob }
      else
        format.html { render :edit }
        format.json { render json: @mrpjob.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mrpjobs/1
  # DELETE /mrpjobs/1.json
  def destroy
    @mrpjob.destroy
    respond_to do |format|
      format.html { redirect_to mrpjobs_url, notice: 'Mrpjob was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mrpjob
      @mrpjob = Mrpjob.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mrpjob_params
      params.require(:mrpjob).permit(:name, :description)
    end

end

app/controllers/runtimes_controller.rb
class RuntimesController < ApplicationController
  skip_before_action :verify_authenticity_token, only:[:create]
  before_action :set_runtime, only: [:show, :edit, :update, :destroy]

  # GET /runtimes
  # GET /runtimes.json
  def index
    @runtimes = Runtime.all.order("created_at DESC")
    @mrpjobs = Mrpjob.all.order('id ASC')
  end

  # GET /runtimes/1
  # GET /runtimes/1.json
  def show
    @mrpjobs = Mrpjob.all.order('id ASC')
  end

  # GET /runtimes/new
  def new
    @runtime = Runtime.new
    @mrpjobs = Mrpjob.all.order("id ASC")
  end

  # GET /runtimes/1/edit
  def edit
    @mrpjobs = Mrpjob.all.order('id ASC')
  end

  # POST /runtimes
  # POST /runtimes.json
  def create
    @runtime = Runtime.new(runtime_params)
    @mrpjobs = Mrpjob.all

    respond_to do |format|
      if @runtime.save
        format.html { redirect_to root_path, notice: 'Runtime was successfully created.' }
        format.json { render :show, status: :created, location: @runtime }
      else
        format.html { render :new }
        format.json { render json: @runtime.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /runtimes/1
  # PATCH/PUT /runtimes/1.json
  def update
    respond_to do |format|
      if @runtime.update(runtime_params)
        format.html { redirect_to @runtime, notice: 'Runtime was successfully updated.' }
        format.json { render :show, status: :ok, location: @runtime }
      else
        format.html { render :edit }
        format.json { render json: @runtime.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /runtimes/1
  # DELETE /runtimes/1.json
  def destroy
    @runtime.destroy
    respond_to do |format|
      format.html { redirect_to mrpjobs_url, notice: 'Runtime was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_runtime
      @runtime = Runtime.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def runtime_params
      params.require(:runtime).permit(:start_time, :end_time, :date, :mrpjob_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
        @mrpjobs = Mrpjob.all.order("id")
        @runtimes = Runtime.all.order("mrpjob_id")

        if params.has_key?(:date)
          @searchdate  = Date.parse params[:date].values.join("-")
        else
          @searchdate = Time.now.to_date
        end

        @runtimewarnings = [["D56TAMPS01", 68],["D56NMRP", 31],["D56KMRP", 67],["D56ZZMRP", 123],["D56XMRP", 41],["D56RMRP", 8],["D56TUMRP", 26],["D56NOMRP", 25],["D56AMRP", 16],["D56CCMRP", 6]]
    end

end

app/views/graph/index.html.erb
<%= form_tag(graph_index_url, method: "get") do %>
  <%= label_tag(:graph_id, "Which job do you want to graph?") %>
  <%= select_tag(:graph_id, options_for_select([['Philippines', 0],
                                            ['Nieuwegein', 1],
                                            ['Kilkeel', 2],
                                            ['Leighton-Buzzard', 3],
                                            ['Lenexa', 4],
                                            ['Rockford', 5],
                                            ['Tucson', 6],
                                            ['Nogales', 7],
                                            ['Anaheim', 8],
                                            ['Commerce Center', 9]], 2)) %>
  <%= submit_tag("Graph") %>
<% end %>
<hr />
<h2><%= @mrpname %></h2>

<svg id="graph"></svg>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Dashboard" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "graph" %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top rc-grey rc-orange">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Dashboard", root_path, :class => "navbar-brand rc-orange" %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Mrp Jobs", mrpjobs_path, :class => "rc-orange" %></li>
            <li><%= link_to "Add New Runtimes", new_runtime_path, :class => "rc-orange"  %></li>
            <li><%= link_to "Graphs", graph_index_url, :class => "rc-orange" %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer class="rc-orange rc-grey footer">
        <p class="text-center"><strong class="rc-orange">&copy;</strong>2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/static.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Dashboard" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Dashboard</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/mrpjobs/_table.html.erb
<%- model_class = Mrpjob -%>
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= model_class.human_attribute_name(:start_time) %></th>
          <th><%= model_class.human_attribute_name(:end_time) %></th>
          <th><%= model_class.human_attribute_name(:date) %></th>
          <th>Completion Time</th>
          <th><%=t '.actions', :default => t("helpers.actions") %></th>
        </tr>
      </thead>
      <tbody>
        <% @sorting.each do |runtime| %>
          <% if @amount.nil? || @amount == 0 %>
            <tr>
              <td><%= runtime.start_time.try(:strftime, '%R') %></td>
              <td><%= runtime.end_time.try(:strftime, '%R') %></td>
              <td><%= runtime.date.try(:strftime, '%D') %></td>
              <td>
                <% if (runtime.start_time > runtime.end_time) %>
                  <%= ((runtime.end_time - runtime.start_time)/60) + 1440 %>
                <% else %>
                  <%= (runtime.end_time - runtime.start_time)/60 %>
                <% end %>
                min
              </td>
              <td>
                <%= link_to t('.edit', :default => t("helpers.links.edit")),
                            edit_runtime_path(runtime), :class => 'btn btn-default btn-xs' %>
                <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                            runtime_path(runtime),
                            :method => :delete,
                            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                            :class => 'btn btn-xs btn-danger' %>
              </td>
            </tr>
          <% elsif (runtime.date > @time_to_sort) %>
            <tr>
              <td><%= Mrpjob.name %></td>
              <td><%= runtime.start_time.try(:strftime, '%R') %></td>
              <td><%= runtime.end_time.try(:strftime, '%R') %></td>
              <td><%= runtime.date.try(:strftime, '%D') %></td>
              <td>
                <% if (runtime.start_time > runtime.end_time) %>
                  <%= ((runtime.end_time - runtime.start_time)/60) + 1440 %>
                <% else %>
                  <%= (runtime.end_time - runtime.start_time)/60 %>
                <% end %>
                min
              </td>
              <td>
                <%= link_to t('.edit', :default => t("helpers.links.edit")),
                            edit_runtime_path(runtime), :class => 'btn btn-default btn-xs' %>
                <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                            runtime_path(runtime),
                            :method => :delete,
                            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                            :class => 'btn btn-xs btn-danger' %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>

app/views/mrpjobs/index.html.erb
<%- model_class = Mrpjob -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <!--<th><%#= model_class.human_attribute_name(:created_at) %></th>-->
      <th class="hide"><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @mrpjobs.each do |mrpjob| %>
      <tr>
        <td><%=  mrpjob.id %></td>
        <td><%= link_to mrpjob.name, mrpjob_path(mrpjob) %></td>
        <td><%= mrpjob.description %></td>
        <!--<td><%#= mrpjob.created_at %></td>-->
        <td><%= mrpjob.runtimes.count %></td>
        <td class="hide">
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_mrpjob_path(mrpjob), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      mrpjob_path(mrpjob),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_mrpjob_path,
            :class => 'btn btn-primary' %>

app/views/mrpjobs/show.html.erb
<%- model_class = Mrpjob -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @mrpjob.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @mrpjob.description %></dd>
  <dt><strong>Running Average:</strong></dt>
  <dd><%= @running_average %> min</dd>
  <dt><strong>Since:</strong></dt>
  <dd><%= @time_to_sort %></dd>
</dl>

<%= form_tag(@mrpjob, method: "get") do %>
  <%= label_tag(:amount, "Sort by days ago:") %>
  <%= text_field_tag(:amount) %>
  <%= submit_tag("Sort") %>
<% end %>
<br >
<%= render 'table' %>

<%= link_to t('.back', :default => t("helpers.links.back")),
              mrpjobs_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_mrpjob_path(@mrpjob), :class => 'btn btn-default hide' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              mrpjob_path(@mrpjob),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger hide' %>

app/views/runtimes/_form.html.erb
<%= form_for @runtime,:remote => true, :html => { :class => "form-horizontal runtime" } do |f| %>

  <% if @runtime.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@runtime.errors.count, "error") %> prohibited this runtime from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @runtime.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

    <div class="row">
      <%#= runtime.id %>
      <%# @mrpjobs.each do |p| %>
        <div class="">
          <%= f.text_field :mrpjob_id, value: runtime.id, :class => 'hide' %>
          <h3><%= f.label :mrpjob_id, runtime.name, :class => 'text-center' %></h3>
        </div>
      <%# end %>
    </div>
    <div class="form-group">
      <%= f.label :start_time, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :start_time, :class => 'form-control' %>
      </div>
      <%=f.error_span(:start_time) %>
    </div>
    <div class="form-group">
      <%= f.label :end_time, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :end_time, :class => 'form-control' %>
      </div>
      <%=f.error_span(:end_time) %>
    </div>
    <div class="form-group">
      <%= f.label :date, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.date_select :date, :class => 'form-control' %>
      </div>
      <%=f.error_span(:date) %>
    </div>

    <div class="form-group hide">
      <div class="col-lg-offset-2 col-lg-10">
        <%= f.submit nil, :class => 'btn btn-primary form' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  runtimes_path, :class => 'btn btn-default' %>
      </div>
    </div>
<% end %>

app/views/runtimes/_form0.html.erb
<%= form_for @runtime, :html => { :class => "form-horizontal runtime" } do |f| %>

  <% if @runtime.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@runtime.errors.count, "error") %> prohibited this runtime from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @runtime.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="col-sm-6 padding">

    <div class="form-group">
      <%= f.label :start_time, :class => 'control-label col-lg-2' %>
      <div class="col-lg-6">
        <%= f.text_field :start_time, :class => 'form-control' %>
      </div>
      <%=f.error_span(:start_time) %>
    </div>
    <div class="form-group">
      <%= f.label :end_time, :class => 'control-label col-lg-2' %>
      <div class="col-lg-6">
        <%= f.text_field :end_time, :class => 'form-control' %>
      </div>
      <%=f.error_span(:end_time) %>
    </div>
    <div class="form-group">
      <%= f.label :date, :class => 'control-label col-lg-2' %>
      <div class="col-lg-6">
        <%= f.text_field :date, :class => 'form-control' %>
      </div>
      <%=f.error_span(:date) %>
    </div>

     <div class="row">
        <% @mrpjobs.each do |p| %>
          <div class="col-sm-2 text-center">
            <%= f.radio_button :mrpjob_id, p.id %>
            <%= f.label :mrpjob_id, p.name %>
          </div>
        <% end %>
    </div>

    <div class="form-group hide">
      <div class="col-lg-offset-2 col-lg-10">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  runtimes_path, :class => 'btn btn-default' %>
      </div>
    </div>
  </div>

<% end %>

app/views/runtimes/edit.html.erb
<%- model_class = Runtime -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form0' %>
<div class="col-lg-offset-2 col-lg-10">
    <%= submit_tag (value = "Save Changes"), :class => 'btn btn-primary form', :id => 'multiSubmit' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                runtimes_path, :class => 'btn btn-default' %>
</div>

app/views/runtimes/index.html.erb
<%- model_class = Runtime -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:Mrpjob_id) %></th>
      <th><%= model_class.human_attribute_name(:start_time) %></th>
      <th><%= model_class.human_attribute_name(:end_time) %></th>
      <th><%= model_class.human_attribute_name(:date) %></th>
      <th>Completion Time</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @sorting.each do |runtime| %>
      <tr>
        <td><%= runtime.Mrpjob.name %></td>
        <td><%= runtime.start_time.try(:strftime, '%R') %></td>
        <td><%= runtime.end_time.try(:strftime, '%R') %></td>
        <td><%= runtime.date.try(:strftime, '%D') %></td>
        <td>
          <% if (runtime.start_time > runtime.end_time) %>
            <%= ((runtime.end_time - runtime.start_time)/60) + 1440 %>
          <% else %>
            <%= (runtime.end_time - runtime.start_time)/60 %>
          <% end %>
          min
        </td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_runtime_path(runtime), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      runtime_path(runtime),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_runtime_path,
            :class => 'btn btn-primary' %>